package com.example.flowobjectrepro

sealed interface Fruit {
    object Apple : Fruit
    object Orange : Fruit
    object Banana : Fruit
    object Mango : Fruit
    object Strawberry : Fruit
    object Pineapple : Fruit
    object Grapes : Fruit
    object Watermelon : Fruit
    object Pear : Fruit
    object Kiwi : Fruit
    object Lemon : Fruit
    object Lime : Fruit
    object Blueberry : Fruit
    object Blackberry : Fruit
    object Peach : Fruit
    object Plum : Fruit
    object Cherry : Fruit
    object Apricot : Fruit
    object Pomegranate : Fruit
    object Fig : Fruit
    object Cranberry : Fruit
    object Papaya : Fruit
    object Guava : Fruit
    object DragonFruit : Fruit
    object PassionFruit : Fruit
    object Lychee : Fruit
    object StarFruit : Fruit
    object Avocado : Fruit
    object Cantaloupe : Fruit
    object Honeydew : Fruit
    object Date : Fruit
    object Jackfruit : Fruit
    object Elderberry : Fruit
    object Gooseberry : Fruit
    object Raspberry : Fruit
    object Blackcurrant : Fruit
    object Clementine : Fruit
    object Tangerine : Fruit
    object Grapefruit : Fruit
    object Pomelo : Fruit
    object Boysenberry : Fruit
    object Mulberry : Fruit
    object Nectarine : Fruit
    object Olive : Fruit
    object Persimmon : Fruit
    object Quince : Fruit
    object UgliFruit : Fruit
    object Feijoa : Fruit
    object Kiwifruit : Fruit
}
